name: factlyapp_landing
description: "FactlyApp Landing page"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

# App version
version: 1.0.2

# Env
environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:

  # Flutter
  flutter:
    sdk: flutter

  # Web plugins used to add path routing support
  flutter_web_plugins:
    sdk: flutter

  # Routing
  go_router: ^17.0.0

  # Localizations
  easy_localization: ^3.0.8

  # Launcher
  url_launcher: ^6.3.2

  # Animations & UI
  flutter_svg: ^2.1.0
  lottie: ^3.3.1
  animated_switcher_plus: ^1.4.0
  animate_do: ^4.2.0
  markdown_widget: ^2.3.2+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  assets:
    - assets/images/
    - assets/animations/
    - assets/translations/
    - assets/icons/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Manrope/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope/Manrope-ExtraBold.ttf
          weight: 800

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
          weight: 700
